spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter_db?useUnicode=true&characterEncoding=utf-8&useSSL=false # replace this with Prod DB config
    username: root
    password: 123456  # update it to your own password
  session:
    timeout: 86400  # session 失效时间
server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: false
